[package]
name = "blinkt"
version = "0.1.0"
authors = ["Ashhhleyyy <ash@ashhhleyyy.dev>"]
edition = "2018"

[lib]
name = "blinkt"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.25.0"
blinkt = "0.6"
lazy_static = "1"
